
MONGODB_SERVER = "192.168.1.9"
MONGODB_PORT = 27017
MONGODB_DB = "gtja"
MONGODB_COLLECTION_REPORT_ABSTRACT = "report_abstract"
MONGODB_COLLECTION_REPORT_FILE = "report_file"
MONGODB_COLLECTION_REPORT_VISITED = "report_visited"
MAX_RECORDS = 100

FILE_PATH = ""