
MONGODB_SERVER = "192.168.1.9"
MONGODB_PORT = 27017
MONGODB_DB = "gtja"
MONGODB_COLLECTION_REPORT_ABSTRACT = "report_abstract"
MONGODB_COLLECTION_REPORT_FILE = "report_file"
MONGODB_COLLECTION_REPORT_VISITED = "report_visited"
MAX_RECORDS = 100

BUCKET_NAME = "database"
OBJECT_REPORT_ABSTRACT = "report_abstract"
OBJECT_REPORT_FILE = "report_file"

EXPIRE_DAYS = 1
FILE_PATH = ""